services:
  product_service:
    build: ./product_service
    container_name: product_service
    # command: uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload
    ports:
      - "8001:8000"
    env_file:
      - ./product_service/.env
    depends_on:
      product_db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 10s
      timeout: 3s
      retries: 5

  product_db:
    image: postgres:15
    container_name: product_db
    ports:
      - "5433:5432"
    env_file:
      - ./product_service/.env
    volumes: # ⬅️ добавлено
      - product_data:/var/lib/postgresql/data # ⬅️ добавлено
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

  order_service:
    build: ./order_service
    container_name: order_service
    # command: uvicorn app.main:app --host 0.0.0.0 --port 8002 --reload
    ports:
      - "8002:8000"
    env_file:
      - ./order_service/.env
    depends_on:
      order_db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 10s
      timeout: 3s
      retries: 5

  order_db:
    image: postgres:15
    container_name: order_db
    ports:
      - "5434:5432"
    env_file:
      - ./order_service/.env
      - ./order_service/.env
    volumes: # ⬅️ добавлено
      - order_data:/var/lib/postgresql/data # ⬅️ добавлено
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

  admin_service:
    build: ./admin_service
    container_name: admin_service
    # command: uvicorn app.main:app --host 0.0.0.0 --port 8003 --reload
    ports:
      - "8003:8000"
    env_file:
      - ./admin_service/.env
    depends_on:
      admin_db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8003/health"]
      interval: 10s
      timeout: 3s
      retries: 5

  admin_db:
    image: postgres:15
    container_name: admin_db
    ports:
      - "5435:5432"
    env_file:
      - ./admin_service/.env
    volumes: # ⬅️ добавлено
      - admin_data:/var/lib/postgresql/data # ⬅️ добавлено
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes: # ⬅️ добавлено
  product_data: # ⬅️ добавлено
  order_data: # ⬅️ добавлено
  admin_data: # ⬅️ добавлено
